# Generated by Django 3.1.12 on 2025-02-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='analysis_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
