# Generated by Django 3.1.12 on 2025-02-24 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analysis', '0002_auto_20250222_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='email',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='name',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='skills',
        ),
    ]
